on:
  release:
    types:
      - created

name: Append phalcon.phar to release

jobs:
  build:
    name: Compile and upload Phar
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PHP 7.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: phalcon-4.0.5

      - name: Compile phalcon.phar
        run: |
          composer install
          wget https://github.com/box-project/box/releases/download/3.9.1/box.phar
          php box.phar compile

      - name: Check existence of compiled .phar
        run: test -e phalcon.phar && exit 0 || exit 10

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./phalcon.phar
          asset_name: phalcon.phar
          asset_content_type: application/octet-stream
